search_term: BTCUSDT
news_sources: ["newsapi", "hackernews"]
start_balance: 10000
order_quantity: 0.01
total_quantity_limit: 1
commission: 0.002
kline_interval: 1m
start_date: 2024-03-15
end_date: 2024-03-20
sentiment_data: ./sentiment_data/sentiment_data.csv
logging_level: DEBUG